FPT: Only flash DESC, ME, and BIOS regions
system76/firmware-update pull request #43
Opened 2021-10-08 20:31 UTC by crawfxrd

Only flash regions that we expect to update.

Platform Data and EC regions are unused. The GbE region, if used, should
not be modified to preserve MAC address, SSIDs, and OEM custom values
set when the chip was originally programmed.

- Do we have any firmware that uses the EC region?
- I only tested on the gaze16. Do any of the other boards lock these regions?

This only works when flashing from proprietary firmware.

On open firmware, FPT cannot be used to flash the regions:

- ME: Cannot find the ME client
- BIOS: Protected Range Registers are set, preventing flash access

2021-10-12 16:09 UTC, jacobgkau commented
Okay, I first checked out https://github.com/system76/firmware/pull/333, then checked out this firmware-update branch, then merged https://github.com/system76/firmware-update/pull/44 into this branch to fix the EC Mismatch error. I'm now seeing `Error 37: Invalid command line option(s).`

![IMG_20211012_100610](https://user-images.githubusercontent.com/7199422/136991761-c60a4cc6-5c3e-4bf6-8c08-3859752c73c9.jpg)

This looks like a problem with the FPT changes, but if the checkout process I described above would cause this, let me know how else I should test.

2021-10-12 16:45 UTC, crawfxrd commented
Looks like FPT can only flash a single region at a time.

2021-10-14 01:12 UTC, jackpot51 approved these changes

2021-11-03 17:43 UTC, leviport approved these changes
Looks good now! I'm not seeing the AccessDenied error any longer, and can successfully flash between proprietary and open firmware on gaze16-3060-b

2021-11-03 17:46 UTC, jackpot51 requested changes
I think Levi saw it work on the gaze16-gbe branch which does not include toolchain updates. We will still need to verify this branch

2021-11-03 17:46 UTC, merged

2021-11-03 17:46 UTC, jackpot51 commented
I don't see any issues with the changes here, per-say. So the issues are already in master. We can address them as part of the firmware-open PR.